package com.mwu.dida.framework.swagger.cofig;

import com.github.xiaoymin.knife4j.spring.configuration.Knife4jAutoConfiguration;
import com.github.xiaoymin.knife4j.spring.extension.Knife4jOpenApiCustomizer;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.media.IntegerSchema;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springdoc.core.customizers.OpenApiBuilderCustomizer;
import org.springdoc.core.customizers.ServerBaseUrlCustomizer;
import org.springdoc.core.models.GroupedOpenApi;
import org.springdoc.core.properties.SpringDocConfigProperties;
import org.springdoc.core.providers.JavadocProvider;
import org.springdoc.core.service.OpenAPIService;
import org.springdoc.core.service.SecurityService;
import org.springdoc.core.utils.PropertyResolverUtils;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Handler;


/*
@AutoConfiguration(before = Knife4jAutoConfiguration.class)

This annotation specifies that this auto-configuration class should be applied before the Knife4jAutoConfiguration class. This ensures that any customizations made in this class take precedence over the default configurations provided by Knife4j.
For example, if you want to override the behavior of Knife4jOpenApiCustomizer, this annotation ensures your changes are applied first.
@ConditionalOnClass({OpenAPI.class})

This annotation ensures that the auto-configuration is only activated if the OpenAPI class is present on the classpath. This is a safeguard to ensure that Swagger/OpenAPI dependencies are available before attempting to configure them.
If the OpenAPI class is missing, this configuration will not be applied.
@EnableConfigurationProperties(SwaggerProperties.class)

This annotation binds the SwaggerProperties class to the Spring environment, allowing you to define Swagger-related properties in your application configuration files (e.g., application.yaml or application.properties).
These properties can then be injected and used within the application.
@ConditionalOnProperty(prefix = "dida.swagger", name = "enabled", havingValue = "true", matchIfMissing = true)

This annotation ensures that the auto-configuration is only applied if the property dida.swagger.enabled is set to true or is missing (defaults to true due to matchIfMissing = true).
This provides a way to enable or disable Swagger configuration dynamically through application properties.
@Import(Knife4jOpenApiCustomizer.class)

This annotation imports the Knife4jOpenApiCustomizer class into the Spring context. This class is likely used to customize the OpenAPI documentation generated by Knife4j.
By importing it here, you ensure that it is available for use in the application.
┌─────────────────────────────────────────────────────────┐
│  阶段 1：条件检查                                          │
│  ├─ @ConditionalOnClass(OpenAPI.class) ✓ 通过            │
│  └─ @ConditionalOnProperty(...) ✓ 通过                   │
├─────────────────────────────────────────────────────────┤
│  阶段 2：排序处理                                          │
│  └─ before = Knife4jAutoConfiguration → 排前面            │
├─────────────────────────────────────────────────────────┤
│  阶段 3：属性绑定                                          │
│  └─ @EnableConfigurationProperties(SwaggerProperties)     │
│     → 绑定 dida.swagger.* 配置到对象                      │
├─────────────────────────────────────────────────────────┤
│  阶段 4：Bean 注册（关键！）                                │
│  └─ @Import(Knife4jOpenApiCustomizer)                     │
│     → 注册 自定义 的 Knife4jOpenApiCustomizer Bean       │
├─────────────────────────────────────────────────────────┤
│  阶段 5：Knife4jAutoConfiguration 执行（后）               │
│  └─ 检测到 Knife4jOpenApiCustomizer 已存在               │
│     → @ConditionalOnMissingBean 条件失败                 │
│     → 跳过创建默认 Bean                                   │
├─────────────────────────────────────────────────────────┤
│  结果：最终使用 DidaSwaggerAutoConfiguration 导入的       │
│        Knife4jOpenApiCustomizer（自定义版本）              │
└─────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────┐
│  @Import 的作用：在 AutoConfiguration 类被处理时               │
│  "顺带"把另一个配置类也加载进来                               │
│                                                             │
│  好处：                                                      │
│  1. Knife4jOpenApiCustomizer 不需要单独写在 spring.factories   │
│  2. 它是 DidaSwaggerAutoConfiguration 的一部分，条件统一控制    │
│  3. 保证顺序：先导入的 Bean 先注册，后续可以覆盖或被检测


┌─────────────────────────────────────────────────────────────────────┐
│  Phase 1: Spring Boot 启动，扫描自动配置                               │
│                                                                     │
│  发现 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports │
│  或 spring.factories 中的 DidaSwaggerAutoConfiguration               │
├─────────────────────────────────────────────────────────────────────┤
│  Phase 2: 处理 DidaSwaggerAutoConfiguration 的条件注解                  │
│                                                                     │
│  1. @ConditionalOnClass(OpenAPI.class)                              │
│     └── ✅ OpenAPI 在 classpath，条件满足                              │
│                                                                     │
│  2. @ConditionalOnProperty(prefix="dida.swagger", ...)              │
│     └── ✅ enabled=true 或缺失，条件满足                               │
├─────────────────────────────────────────────────────────────────────┤
│  Phase 3: 处理 @Import(Knife4jOpenApiCustomizer.class) ⭐ 关键！       │
│                                                                     │
│  @Import 会立即加载 Knife4jOpenApiCustomizer 并注册其中的 Bean          │
│                                                                     │
│  Knife4jOpenApiCustomizer 中：                                        │
│  ├─ @Configuration 被解析                                            │
│  ├─ 构造器执行（ObjectProvider 获取依赖）                               │
│  └─ Bean 被注册到 Spring 容器                                         │
├─────────────────────────────────────────────────────────────────────┤
│  Phase 4: 处理 DidaSwaggerAutoConfiguration 其他注解                    │
│                                                                     │
│  @EnableConfigurationProperties(SwaggerProperties.class)            │
│  └── 绑定 dida.swagger.* 配置到 SwaggerProperties 对象                 │
├─────────────────────────────────────────────────────────────────────┤
│  Phase 5: 后续自动配置（根据 before/after 排序）                        │
│                                                                     │
│  @AutoConfiguration(before = Knife4jAutoConfiguration.class)        │
│  └── 确保在 Knife4jAutoConfiguration 之前处理（已处理完）                │
│      └── Knife4jAutoConfiguration 检测 Knife4jOpenApiCustomizer 已存在   │
│          └── 跳过创建默认 Bean                                        │
└─────────────────────────────────────────────────────────────────────┘

 */
@AutoConfiguration(before = Knife4jAutoConfiguration.class) // before 原因，保证覆写的 Knife4jOpenApiCustomizer 先生效！相关 https://github.com/YunaiV/ruoyi-vue-pro/issues/954 讨论
@ConditionalOnClass({OpenAPI.class})
@EnableConfigurationProperties(SwaggerProperties.class)
@ConditionalOnProperty(prefix = "dida.swagger", name = "enabled", havingValue = "true", matchIfMissing = true)
@Import(Knife4jOpenApiCustomizer.class)
public class DidaSwaggerAutoConfiguration {

    @Bean
    public OpenAPI createApi(SwaggerProperties properties) {
        Map<String, SecurityScheme> securitySchemes = buildSecuritySchemes();
        OpenAPI openAPi = new OpenAPI()
                .info(buildInfo(properties))
                .components(new Components().securitySchemes(securitySchemes))
                .addSecurityItem(new SecurityRequirement().addList(HttpHeaders.AUTHORIZATION));
        securitySchemes.keySet().forEach(key -> openAPi.addSecurityItem(new SecurityRequirement().addList(key)));

        )
    }

    private Info buildInfo(SwaggerProperties properties) {
        return new Info()
                .title(properties.getTitle())
                .description(properties.getDescription())
                .version(properties.getVersion())
                .contact(new Contact().name(properties.getAuthor()).url(properties.getUrl()).email(properties.getEmail()))
                .license(new License().name(properties.getLicense()).url(properties.getLicenseUrl()));
    }
    private Map<String, SecurityScheme> buildSecuritySchemes() {
        Map<String, SecurityScheme> securitySchemes = new HashMap<>();
        SecurityScheme securityScheme = new SecurityScheme()
                .type(SecurityScheme.Type.APIKEY)
                .name(HttpHeaders.AUTHORIZATION)
                .in(SecurityScheme.In.HEADER);
        securitySchemes.put(HttpHeaders.AUTHORIZATION, securityScheme);
        return securitySchemes;
    }

    /**
     * 自定义 OpenAPI 处理器
     */
    @Bean
    @Primary // 目的：以我们创建的 OpenAPIService Bean 为主，避免一键改包后，启动报错！
    public OpenAPIService openApiBuilder(Optional<OpenAPI> openAPI,
                                         SecurityService securityParser,
                                         SpringDocConfigProperties springDocConfigProperties,
                                         PropertyResolverUtils propertyResolverUtils,
                                         Optional<List<OpenApiBuilderCustomizer>> openApiBuilderCustomizers,
                                         Optional<List<ServerBaseUrlCustomizer>> serverBaseUrlCustomizers,
                                         Optional<JavadocProvider> javadocProvider) {
        return new OpenAPIService(openAPI, securityParser, springDocConfigProperties,
                propertyResolverUtils, openApiBuilderCustomizers, serverBaseUrlCustomizers, javadocProvider);
    }

    @Bean
    public GroupedOpenApi allGroupedOpenApi() {
        return buildGroupedOpenApi("all", "");
    }

    public static GroupedOpenApi buildGroupedOpenApi(String group {
        return buildGroupedOpenApi(group, group);
    }

    public static GroupedOpenApi buildGroupedOpenApi(String group, String path) {
        return GroupedOpenApi.builder()
                .group(group)
                .pathsToMatch("/admin-api/" + path + "/**", "/app-api/" + path + "/**")
                .addOperationCustomizer((operation, handlerMethod) -> operation
                        .addParametersItem(buildTenantHeaderParameter())
                        .addParametersItem(buildSecurityHeaderParameter()))
                .addOperationCustomizer(buildOpetationIdCustomizer())
                .build();
    }

    public static Parameter buildTenantHeaderParameter() {
        return new Parameter()
                .name(HEADER_TENANT_ID)
                .description("租户ID")
                .in(String.valueOf(SecuritySchemeIn.HEADER)
                .schema(new IntegerSchema()._default(1L).name(HEADER_TENANT_ID).description("租户ID"));

    }
}
